# Generated by Django 3.2.23 on 2023-12-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website',
            options={'ordering': ('created',), 'verbose_name': 'Вебсайты клиентов'},
        ),
        migrations.AddField(
            model_name='website',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default='2023-12-28 09:00:00.000000+00:00', verbose_name='Время добавления сайта'),
            preserve_default=False,
        ),
    ]
