# Generated by Django 3.2.23 on 2024-01-22 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_auto_20231227_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website',
            options={'ordering': ('-created',), 'verbose_name': 'Вебсайты клиентов'},
        ),
    ]
