# Generated by Django 3.2.23 on 2023-12-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Админ'), ('CUSTOMER', 'Клиент')], default='CUSTOMER', max_length=20),
        ),
    ]
